---
name: 'build-and-push-to-github'
description: 'Build and push a Docker Image'
inputs:
  image-name: 
    description: 'Image to build and push'
    required: true
  username:
    description: 'Username to login to Github registry'
  password:
    description: 'Token to login to Github Registry'

runs:
  using: "composite"
  steps:
    - name: Login to GHCR 
      run: |
        docker login ghcr.io -u ${{ inputs.username }} -p ${{ inputs.password }}
      shell: bash

    - name: Docker build
      run: |
        docker build -t kuent1/buildandpush/${{ inputs.image-name }} .
      shell: bash