---
name: 'build-and-push-to-github'
description: 'Build and push a Docker Image'

inputs:
  image-name: 
    description: 'Image to build and push'
    required: true
  registry:
    description: 'Which registry to push on'
    default: ghcr.io
    required: false
  username:
    description: 'Username to login to Github registry'
  password:
    description: 'Token to login to Github Registry'

runs:
  using: "composite"
  steps:
    - name: Login to GHCR 
      run: |
        docker login ${{ inputs.registry }} -u ${{ inputs.username }} -p ${{ inputs.password }}
      shell: bash

    - name: Docker build
      run: |
        docker build -t ${{ inputs.registry }}/kuent1/buildandpush/${{ inputs.image-name }} .
      shell: bash