on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test job
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Test the login
      uses: ./
      with:
        image-name: monimage
        username: Kuent1
        password: ${{ secrets.GITHUB_TOKEN }}